# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'DragDropStackView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DragDropStackView
  pod 'RxSwift', '~> 6.8.0'
  pod 'RxCocoa', '~> 6.8.0'
  pod 'RxGesture', '~> 4.0.4'
  pod 'SnapKit', '~> 5.7.1'

end
